"""
criaturas_diccionario = {
    'Ceto': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Tifón': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Zeus'},
    'Equidna': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Argos Panoptes'},
    'Dino': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Pefredo': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Enio': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Escila': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Caribdis': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Euríale': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Esteno': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Medusa': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Perseo'},
    'Ladón': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Heracles'},
    'Águila del Cáucaso': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Quimera': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Belerofonte'},
    'Hidra de Lerna': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Heracles'},
    'León de Nemea': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Heracles'},
    'Esfinge': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Edipo'},
    'Dragón de la Cólquida': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Cerbero': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Cerda de Cromión': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Teseo'},
    'Ortro': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Heracles'},
    'Toro de Creta': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Teseo'},
    'Jabalí de Calidón': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Atalanta'},
    'Carcinos': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Gerión': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Heracles'},
    'Cloto': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Láquesis': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Átropos': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Minotauro de Creta': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Teseo'},
    'Cierva Cerinea': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Argos Panoptes': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Hermes'},
    'Aves del Estínfalo': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Talos': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Medea'},
    'Sirenas': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Pitón': {'Descripcion': '-', 'DerrotadoPorHeroe': 'Apolo'},
    'Cierva de Cerinea': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Basilisco': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
    'Jabalí de Erimanto': {'Descripcion': '-', 'DerrotadoPorHeroe': None},
}
"""
criaturas_lista = [
    {'name': 'Ceto', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Tifón', 'descripcion': '-', 'derrotadoPorHeroe': 'Zeus'},
    {'name': 'Equidna', 'descripcion': '-', 'derrotadoPorHeroe': 'Argos Panoptes'},
    {'name': 'Dino', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Pefredo', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Enio', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Escila', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Caribdis', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Euríale', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Esteno', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Medusa', 'descripcion': '-', 'derrotadoPorHeroe': 'Perseo'},
    {'name': 'Ladón', 'descripcion': '-', 'derrotadoPorHeroe': 'Heracles'},
    {'name': 'Águila del Cáucaso', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Quimera', 'descripcion': '-', 'derrotadoPorHeroe': 'Belerofonte'},
    {'name': 'Hidra de Lerna', 'descripcion': '-', 'derrotadoPorHeroe': 'Heracles'},
    {'name': 'León de Nemea', 'descripcion': '-', 'derrotadoPorHeroe': 'Heracles'},
    {'name': 'Esfinge', 'descripcion': '-', 'derrotadoPorHeroe': 'Edipo'},
    {'name': 'Dragón de la Cólquida', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Cerbero', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Cerda de Cromión', 'descripcion': '-', 'derrotadoPorHeroe': 'Teseo'},
    {'name': 'Ortro', 'descripcion': '-', 'derrotadoPorHeroe': 'Heracles'},
    {'name': 'Toro de Creta', 'descripcion': '-', 'derrotadoPorHeroe': 'Teseo'},
    {'name': 'Jabalí de Calidón', 'descripcion': '-', 'derrotadoPorHeroe': 'Atalanta'},
    {'name': 'Carcinos', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Gerión', 'descripcion': '-', 'derrotadoPorHeroe': 'Heracles'},
    {'name': 'Cloto', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Láquesis', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Átropos', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Minotauro de Creta', 'descripcion': '-', 'derrotadoPorHeroe': 'Teseo'},
    {'name': 'Cierva Cerinea', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Argos Panoptes', 'descripcion': '-', 'derrotadoPorHeroe': 'Hermes'},
    {'name': 'Aves del Estínfalo', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Talos', 'descripcion': '-', 'derrotadoPorHeroe': 'Medea'},
    {'name': 'Sirenas', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Pitón', 'descripcion': '-', 'derrotadoPorHeroe': 'Apolo'},
    {'name': 'Cierva de Cerinea', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Basilisco', 'descripcion': '-', 'derrotadoPorHeroe': None},
    {'name': 'Jabalí de Erimanto', 'descripcion': '-', 'derrotadoPorHeroe': None},
]